### ISSUE TITLE
AMD 15h freezes while "Testing: 4096M - 6144M of 15GB RAM (= 16GB - iGPU_shared)"

### ISSUE THREAD

**Issue by mikebdp2** [anphsw/memtest86#14]
Dear @anphsw , thank you for continuing the memtest development! _(yours is the only alive version)_. Your test always freezes instantly after reaching the following memory range:

"Testing: 4096M - 6144M of 15GB RAM (= 16GB - iGPU_shared)"

that's no matter what I do: even if skip a current test (the next will freeze at the same moment), or enable safe mode, or multithreading. Meanwhile, all the other versions - official 4.37 and official 5.01 - are working fine at the same hardware:

* Lenovo G505S laptop with a coreboot opensource BIOS installed
* AMD A10-5750M (Richland 15h architecture)
* Bolton A76M chipset (similar to Hudson)
* two sticks of 8GB DDR3 SO-DIMM Kingston KHX1600C9S3L/8G running as 1600MHz CL9
* bootable media: built a memtest.bin floppy, expanded it to 1.44MB and inserted to a BIOS

By the way, if I quickly skip 3 tests (before reach this freezing moment), Test number 4 is "Test is missing!".

Freezes: I mean, the whole screen freezes and all the values/time are staying the same, only a + is blinking at top left corner besides a Memtest86 logo.

Is there any way to provide more debug info? If you have any ideas, I'm ready to test any custom floppy versions with more debug info collection included.

**Comment by anphsw** [comment]
Hello!
The main word in your issue is "Lenovo". I tested lenovo laptops such T410, T420, X201, X240 and they all act same. I think some IO ports mapped behind 1024K range and BIOS not claimed them (or we cannot parse info correctly) as reserved.
Sometimes writing to that ports hangs whole laptop, keyborad, or EC interaction, sometimes just give memory error (more often this happen at 1.4M addresses).
You can confirm that by pressing "C -> 2 -> 1" and setting lower limit to "16M" or "256M".
It's same issue if test will be passed normally.
Of course we can blacklist such addresses, but no guarantee, that addresses is same on all laptops. We even cannot detect if we run on laptop/PC/server, they all marked as "lenovo XXXX" in bios info.
About test number 4: in original memtest86+ that test also missing, description is also missing, and if you select "test 4" code will jump to "test 5", but numbers are confusing, so you can even know which test number you run. I just added "test is missing" as copy of test 5, so numbers 1-11 from original memtest86+ is same (numbers 12,13 is for rowhammer and latency tests, that missing in original code).

**Comment by mikebdp2** [comment]
@anphsw 
```
I tested lenovo laptops such T410, T420, X201, X240 and they all act same
```
Many Lenovo laptops have UEFI from the same company - InsydeH2O - so many of their proprietary UEFI bugs are the same. However, at my Lenovo G505S I've replaced its' proprietary UEFI with an opensource coreboot BIOS - with a really different codebase (and much higher quality, I believe), so the behaviour should be different. Also:

If there's also such a BIOS bug, why any other memtests (original 4.37/5.01/etc) do not expose it?

Now I tried doing your suggested configuration change, but for some reason - no matter what a range I specify - it instantly freezes (much faster than if I do something else) and a range is 0K - 32M (32M of 15G). Any ideas?

**Comment by anphsw** [comment]
> If there's also such a BIOS bug, why any other memtests (original 4.37/5.01/etc) do not expose it?
Maybe it's not a same bug. It can be memtest bug, but i am not faced it before. Maybe it's releated to compatibility with AMD CPU, as my laptops all based on intel.
You referenced memtest 4.37, but it is not memtest86+, it's passmark memtest86, as last memtest86+ 4x version is 4.20. Its'very stable, but cannot detect some errors.

Is it hangs even while you select harmless range such "500M-501M" or test 12 (latency)?
If you use precompiled binary, please build it with your local GCC, maybe problem is my GCC.

Try both builds (original debian, and vanilla 5.01 compiled with my GCC) to exclude GCC problems.
[memtest.zip](https://github.com/anphsw/memtest86/files/4412529/memtest.zip)

**Comment by anphsw** [comment]
> range is 0K - 32M (32M of 15G). Any ideas?

It seems like you entered upper limit, not lower, recheck it by entering twice to that menu, on second try you will see new limit you set

**Comment by anphsw** [comment]
Please reopen if you have new information.
